### ISSUE TITLE
Season Issue

### ISSUE THREAD

**Issue by LokeYourC3PH** [PTCE-Public/popcorn-desktop#24]
So for some TV series, i noticed that the season counter is wrong. Last Week Tonight says 3, but only has 2 (it actually has 3, and on the old PopcornTime CE version, i could watch the 3rd season, but since i updated from 0.3.1 to 0.3.9, i am unable to watch the 3rd season, its just not there).

**Comment by YIFYtorrents** [comment]
The issue is caused by the external series API but you can use the built-in kat.cr search or change your default API in your settings to get other sources.

**Comment by Breaking1** [comment]
@Yanniclord i would recommend this tv show api, it has most of the tv shows and updates every 30 minutes.

http://api.popcorn.koashiko.xyz/

Go to settings and check the show advanced settings box. Scroll down to connection and change it with the line where it says tv show API endpoint.

Or use the Torrent collection like @YIFYtorrents said and search for any missing content with Kickass until the issue is resolved.

I know they are working on a new tv show API that soon will be implemented that will fix many of the problems with missing shows/episodes.

**Comment by LokeYourC3PH** [comment]
Ok thanks, the TV API you gave me seems to be even worse, at least for Last Week Tonight. It only has the 7th Episode from Season 1, and only some from Season 2. Season 3 does not even exist. What changed from version 0.3.1 to 0.3.9 with the API? Did they change it, and in case, what was the TV API for 0.3.1?

**Comment by Breaking1** [comment]
That API is not from the team but from another source.

What they have changed i have no idea. I guess if you try their discuss forum someone from the team might give you an answer.
